snd-soc-simple-card-utils-objs	:= simple-card-utils.o
snd-soc-simple-card-objs	:= simple-card.o
snd-soc-botic-objs	:= botic-card.o

obj-$(CONFIG_SND_SIMPLE_CARD_UTILS)	+= snd-soc-simple-card-utils.o
obj-$(CONFIG_SND_SIMPLE_CARD)		+= snd-soc-simple-card.o
obj-$(CONFIG_SND_BOTIC_CARD)	+= snd-soc-botic.o
